# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nHc69p6-y5_OAvq2b6rM6C28EVCP10GY
"""

import math

# PalmerPenguinsM2.py
# Pamela Brauda
# 10/03/2026
# Calculates and displays Palmer Penguin statistics.

#Constants representing the names and total of species
SP_CHINSTRAP = "Chinstrap"
SP_GENTOO = "Gentoo"
SP_ADELIE = "Adelie"

TOTAL_SPECIES = 3

numChinstrap = 68
numGentoo = 123
numAdelie = 151

#Calculating the total and avergae of penguin species.
totalPenguins = numChinstrap + numGentoo + numAdelie
avgPenguins = totalPenguins / TOTAL_SPECIES

#Percent of each penguin species.
chinstrapPercent = (numChinstrap / totalPenguins) * 100
gentooPercent = (numGentoo / totalPenguins) * 100
adeliePercent = (numAdelie / totalPenguins) * 100

#Average of penguin species rounded up.
avgPenguinsRoundedUp = math.ceil(avgPenguins)

#Output the names with introduction text
print("Introducing the Palmer Penguins:")
print("\t" + SP_CHINSTRAP + "!")
print("\t" + SP_GENTOO + "!")
print("and last but not least...")
print("\t" + SP_ADELIE + "!")
print()

#Output of calcutions
print("There are a total of " +
      str(TOTAL_SPECIES) +
      " penguin species in this dataset.")
print("There are a total of " +
      str(totalPenguins) +
      " penguin in this dataset.")
print("The average number of penguins per species is " +
      str(avgPenguins) + ".")
print("The average rounded up is " +
      str(avgPenguinsRoundedUp) +
      " penguins.")
print()
print("Chinstrap:", numChinstrap, f"({chinstrapPercent}%)")
print("Gentoo:", numGentoo, f"({gentooPercent}%)")
print("Adelie:", numAdelie, f"({adeliePercent}%)")